### ISSUE TITLE
A small problem about the paper

### ISSUE THREAD

**Issue by SoluMilken** [MiuLab/KB-InfoBot#1]
At the end of section 4.3 `Soft-KB Lookup + Summary`, you mentioned that the final summary vector is 
tilde_s^t =  [H(tilde_p^t_1), H(tilde_p^t_2), ..., H(tilde_p^t_M), q^t_1, q^t_2, ..., q^t_M, H(p^t_mathcal(T)].
I am wondering how to get tilde_p^t_i for i =1, ...M ?
Does it come from (8) ?? 
Thx!!

**Comment by bdhingra** [comment]
Hi, yes that is correct. \tilde{p}^t_i (v) = w^t_i (v) / Z, where Z is the normalization constant.
